---
- name: Check if PiVPN is installed
  ansible.builtin.stat:
    path: /usr/local/bin/pivpn
  register: pivpn_file_stat

- name: Run PiVPN Installer
  ansible.builtin.include_tasks: install.yaml
  when: not pivpn_file_stat.stat.exists